# Site Info
title:              "Isatou"
description:        "In Search of Pure Matter"
author_name:        "Isatou Saho" 
logo_url:            https://avatars.githubusercontent.com/u/247718759?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://pure-matter.github.io # main url
baseurl:            /Isatou
permalink:          /:title # Post permalink
timezone:           America/Recife # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain
collections:
  researches:
    output: true
    permalink: /researches/:name
  projects:
    output: true
    permalink: /projects/:name
  talks:
    output: true
    permalink: /talks/:name
  blog:
    output: true
    permalink: /blog/:name

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      type:         "researches"
    values:
      layout:       "research-post"
  -
    scope:
      type:         "projects"
    values:
      layout:       "post"
  -
    scope:
      type:         "talks"
    values:
      layout:       "post"
  -
    scope:
      type:         "blog"
    values:
      layout:       "post"
